### ISSUE TITLE
Fuzzy logic for decision making in drinking water catchments 

### ISSUE THREAD

**Issue by Almaarofi** [quantsquills/meetups#11]

**Comment by drzax** [comment]
Hi Almaarofi—this sounds intriguing. Could you provide a little more information about what you're proposing? Is this a talk proposal?

**Comment by Almaarofi** [comment]
Hi Simon,

Thank you for your email.

I think I've made a little mistake :) I initially wanted to ask the group a
question and it appears that I was in the wrong place, I tried to delete
the discussion but I couldn't :)
Anyway, I am so pleased that you sent an email so I can ask you directly if
you don't mind! I wonder if the group have done a previous Fuzzy
discussion? and if so I wanted to talk to these experts about my research
project!

It will be great if you can help or advise.
Thank you again

Kind regards
Huda



*Huda Almaarofi | PhD Candidate *

*School of Engineering*
*Griffith University **| Nathan | QLD 4111 | Cities Research Institute
(N78) Room 3.28*
*T +61 (0)7 3735 7037 **| email huda.almaarofi@griffithuni.edu.au
<huda.almaarofi@griffithuni.edu.au>*
*Mobile* *0411 822 524*

**Comment by drzax** [comment]
Ahh, no probs. I don't think there have been any presentations specifically on fuzzy logic, but if you're keen to continue the conversation, I'd suggest joining https://storieswithdata.community and asking there.
