### ISSUE TITLE
November 2018: Satellite Journalism - The Big Picture

### ISSUE THREAD

**Issue by drzax** [quantsquills/meetups#19]
Satellite journalism with Mark Corcoran.

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* [x] Lock in speaker
* [x] Get talk summary and any neat images available
* [x] Add details to Meetup.com
* [ ] Post event to Facebook

## 2 weeks out

* [x] Schedule appropriate tweets for promotion (in TweetDeck)
* [ ] Schedule appropriate FB posts for promotion
* Notify event partners about the event topic for cross promotion
  * [x] Women In Media

## 1 week out

* Post request for volunteers on Facebook and Twitter
  * [ ] Record
  * [ ] Photograph
* [ ] Check catering stock and order more if required

## Day before

* [ ] Check venue details
* [ ] Create intro slides

## Day of

* [ ] Purchase ice
* [ ] Setup venue (start about 4:30pm)
* [ ] Check of attendees on arrival

**Comment by drzax** [comment]
I finally got this one locked in and the details all up on meetup.

@antmandan — I think this one would be particularly ripe for promotion around university circles. Any chance you could give it a push to the right people at UQ/QUT?

**Comment by antmandan** [comment]
Done, I've sent it to UQ/QUT/Griffith. I won't be there this week but hoping that some of my academic peeps will make it along as it looks excellent.

**Comment by drzax** [comment]
I'm closing this, but I'd still like to get Mark for a future event.
