### ISSUE TITLE
Making the jump to data/technical journalism

### ISSUE THREAD

**Issue by drzax** [quantsquills/meetups#3]
**Talk Length:** 40mins + Q&A

**Summary:** A panel session with 4-5 people who have come from more traditional journalism to be leaders in the use of technical skills and tools in the reporting and production of their journalism.

Aiming for June 2018.

**Comment by drzax** [comment]
I'm keen to get organisation for this underway—I think it should be doable to put together a panel by June. I have a couple of people in mind, but would welcome other suggestions.

@rosieryan Are you interested in organising and/or moderating this one?

**Comment by drzax** [comment]
I had a chat to @CristenT about this. She could be tempted onto the panel. 

I think if we can lock in one or two people before next Wednesday we should commit to this as the June event.

**Comment by antmandan** [comment]
Great idea for a panel. Happy to help locate speakers if required but it sounds like you've got it well in hand.

**Comment by drzax** [comment]
Felicity Caldwell has indicated she'd be up for being on the panel.

**Comment by rosieryan** [comment]
@drzax I'm keen to moderate and think Cristen and Felicity would be great panellists. I'll get in touch with them and have a think about some other people to approach. Let me know if you have ideas.

**Comment by drzax** [comment]
I think we should lock this in for June, so I've created an event ticket in #6—lets move further discussion there.
